"""Initial migration

Revision ID: 0d69b87cfa18
Revises: 
Create Date: 2026-02-24 20:36:35.589234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d69b87cfa18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_career_roles_role_id'), 'career_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_career_roles_role_name'), 'career_roles', ['role_name'], unique=True)
    op.create_table('skills',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_index(op.f('ix_skills_skill_id'), 'skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skills_skill_name'), 'skills', ['skill_name'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('predicted_role', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('prediction_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_predictions_prediction_id'), 'predictions', ['prediction_id'], unique=False)
    op.create_table('resumes',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('upload_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('resume_id')
    )
    op.create_index(op.f('ix_resumes_resume_id'), 'resumes', ['resume_id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('skills_to_learn', sa.Text(), nullable=True),
    sa.Column('courses', sa.Text(), nullable=True),
    sa.Column('projects', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['career_roles.role_id'], ),
    sa.PrimaryKeyConstraint('roadmap_id')
    )
    op.create_index(op.f('ix_roadmaps_roadmap_id'), 'roadmaps', ['roadmap_id'], unique=False)
    op.create_table('role_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('importance_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['career_roles.role_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_skills_id'), 'role_skills', ['id'], unique=False)
    op.create_table('user_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('proficiency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skills_id'), 'user_skills', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_skills_id'), table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_role_skills_id'), table_name='role_skills')
    op.drop_table('role_skills')
    op.drop_index(op.f('ix_roadmaps_roadmap_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_resumes_resume_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_predictions_prediction_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_skill_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_skill_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_career_roles_role_name'), table_name='career_roles')
    op.drop_index(op.f('ix_career_roles_role_id'), table_name='career_roles')
    op.drop_table('career_roles')
    # ### end Alembic commands ###
